apiVersion: v1
kind: Pod
metadata:
  name: test-downloadapi-volume
  labels:
    app: test-downloadapi-volume
    zone: use-est-coast
    cluster: test-cluster1
    rack: rack-22
spec:
  containers:
    - name: test-downloadapi-volume
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - "sh"
        - "-c"
      args:
        - while true; do
          if [[ -e /etc/podinfo/labels ]]; then
          echo -en '\n\n'; cat /etc/podinfo/labels; fi;
          sleep 5;
          done;
      volumeMounts:
        - mountPath: /etc/podinfo
          name: podinfo
  restartPolicy: Always
  volumes:
    - name: podinfo
      projected:
        sources:
          - downwardAPI:
              items:
                - path: "labels"
                  fieldRef:
                    fieldPath: metadata.labels
